### ISSUE TITLE
Add subfunction for prep course

### ISSUE THREAD

**Issue by cimendes** [LDSSA/ldsagrader#6]
TBD

Containing only the necessary functions to grade the notebook and return a grade.

**Comment by buedaswag** [comment]
i'm trying to grade a notebook locally with this code, but im getting an error.
am i missing something?
@hcastilho do you have any suggestions?

```python
from nbgrader import utils

def grade(nb):
    total_score = 0
    max_total_score = 0
    for cell in nb.cells:
        if utils.is_grade(cell):
            score, max_score = utils.determine_grade(cell)
            total_score += score
            max_total_score += max_score

    return total_score, max_total_score

from traitlets.config import Config
import nbconvert

#####

def execute(notebook, timeout=None, allow_errors=True):
    c = Config()
    c.NotebookExporter.preprocessors = [
        "nbconvert.preprocessors.ClearOutputPreprocessor",
        "nbconvert.preprocessors.ExecutePreprocessor",
    ]
    c.ExecutePreprocessor.allow_errors = allow_errors
    if timeout:
        c.ExecutePreprocessor.timeout = timeout

    exporter = nbconvert.NotebookExporter(config=c)
    notebook, _ = exporter.from_notebook_node(notebook)

    return nbformat.reads(notebook, as_version=nbformat.NO_CONVERT)

####

import nbformat

notebook_path = 'Exercise notebook.ipynb'
notebook = nbformat.read(notebook_path, as_version=nbformat.NO_CONVERT)
notebook = execute(notebook, timeout=60) # utils.execute(notebook, timeout)
total_score, max_score = grade(notebook)

```

```bash
Traceback (most recent call last):
  File "grade.py", line 40, in <module>
    notebook = execute(notebook, timeout=60) # utils.execute(notebook, timeout)
  File "grade.py", line 30, in execute
    notebook, _ = exporter.from_notebook_node(notebook)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 578, in run_cell
    exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
  File "/home/mig/.virtualenvs/grading-notebooks-locally/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 479, in _poll_for_reply
    if msg['parent_header'].get('msg_id') == msg_id:
TypeError: 'coroutine' object is not subscriptable
sys:1: RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
```

**Comment by hcastilho** [comment]
This is due to problems with lib versions, jupyter-client I think.

**Comment by buedaswag** [comment]
managed to fix it with `jupyter_client==6.1.12`, thanks @hcastilho !

**Comment by buedaswag** [comment]
found the answer here https://github.com/jupyter/jupyter_client/issues/637

**Comment by cimendes** [comment]
🕵🏻
